### ISSUE TITLE
Issue with multiple multiselects on one page

### ISSUE THREAD

**Issue by EasyAsABC123** [yanickrochon/jquery.uix.multiselect#1]
when i have multiple multiselects on one page and i press selectall, deselectall, or search it refreshes all the multiselects.

**Comment by yanickrochon** [comment]
Thank you for pointing that out. I should add in the README that this widget is still in it's early development stage. I shall rectify that with the next commit. And also look at this issue. I am currently implementing the "item disabled" feature and can reproduce what you are experiencing.

**Comment by EasyAsABC123** [comment]
Works much better than version one overall.  Thanks for your hard work!

**Comment by yanickrochon** [comment]
The new push should correct the issue. Also, disabled items support is implemented (not fully tested). Tell me if this fixes the problem for you.

**Comment by EasyAsABC123** [comment]
Resolved!  Below is the example i used, i made you index.php a normal html file so php isn't required.

But i can't seem to upload it.  I can share it with you if need be.  Just needs a couple more options I editted it to have disable button capability.

**Comment by yanickrochon** [comment]
Yes, the PHP file could (should) be replaced by a regular HTML file, I agree. I will do that with the next commit. I have used index.php to test between a large set of data and a more conventional one. I guess, if needed, I could add another HTML file for it instead, then (ex: biglist.html)
