### ISSUE TITLE
feature request: option to switch "selected" and "available" option from left to right

### ISSUE THREAD

**Issue by ghost** [yanickrochon/jquery.uix.multiselect#10]
Hello,

thanks for continuing multiselect "next" development !!!!!
can you please somehow add an option, to switch "selected" and "available" from left to right.
we want it the other way :-)

thanks,
Sam

**Comment by yanickrochon** [comment]
Hi!

You will be pleased to know that this feature is being tested now! It's in the [dev](https://github.com/yanickrochon/jquery.multiselect-2/tree/dev) branch at the moment. It will put into master pretty soon as it seems to work alright. The only delay is a bug ( #8 that will be fixed within the next hours) right now and some new CSS rules have to be tested also.

**Comment by yanickrochon** [comment]
I just pushed the dev branch into master with this feature implemented. Although I missed the icons order... I will do that before tomorrow night. Consider this as closed.
