### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by srepn** [yanickrochon/jquery.uix.multiselect#105]
I try to integrate this solution for my wordpress plugin ( dashboard ), but I get issue: sortable functionality won't work.
I find that behavior of sorting like for list with "Disabled Options".
How can I debug sortable?

**Comment by yanickrochon** [comment]
Did you resolve your issue?

**Comment by srepn** [comment]
HI! Yes, thanks, just thinking  that sortable argument is true by default.

2016-07-08 15:20 GMT+03:00 Yanick Rochon notifications@github.com:

**Comment by srepn** [comment]
HI! Just one question.
Does library have an API to change sortable effect, just like move effect?

2016-07-08 15:41 GMT+03:00 Sergey Repin repin.sergey@gmail.com:
