### ISSUE TITLE
Formatting at bottom of the widget is not right

### ISSUE THREAD

**Issue by wmerrell** [yanickrochon/jquery.uix.multiselect#12]
I looks to me that there is a minor formatting error in the creation of the widget. On my browser it looks like the bottom of the widget is truncated. The css seems to indicate that there should be a border at the bottom and there is not. It looks like the div#multiselect0_avListContent and div#multiselect0_selListContent appear to be miscalculated. On your demo page, using Firebug, I looked at these and they are set with a height of 175px. If I change it to 174px the bottom border appears and the widget looks better I think.

**Comment by yanickrochon** [comment]
If there is no feedback on this within the next 5 days, I'll assume that this issue has been resolved.

**Comment by wmerrell** [comment]
I'll check when I get a chance, a day or two. Thanks.
