### ISSUE TITLE
Question: Working with 2 Lists

### ISSUE THREAD

**Issue by fabiocastaneda** [yanickrochon/jquery.uix.multiselect#13]
Hi Yanick!

Thank you for sharing your widget jquery.multiselect-2

I was wonder if you could you help me in the following issue:

I am trying to use your widget to interact with 2 lists as shown in the following diagram.

STEP 1

Sequence 1 : We select an item from LIST 1
Sequence 2 : We hide the same item from available options on LIST 2

STEP 2 (inverse process)

Sequence 1 : We Unselect an item from selected options on LIST 1
Sequence 2 : We now show the same item on the available options on LIST 2

I have done some work on this. I am able to control items on any single list but I have not figured out how to interact with the second list at the same time.

Any ideas or hints on how to do this?

Thank you very much for your help.

Regards

Fabio

![step1](https://f.cloud.github.com/assets/3435848/113885/749634a6-6b7f-11e2-8224-cc4413679218.gif)

![step2](https://f.cloud.github.com/assets/3435848/113889/83ca3418-6b7f-11e2-987b-116b039ea7e4.gif)

**Comment by yanickrochon** [comment]
HI Fabio,

I'll try to provide you with an example as soon as I can.

BTW: what browser are you using? The rendering is different on my machine. I would also try to fix that problem as well.

**Comment by yanickrochon** [comment]
Hi, take a look at the wiki, I have created a new "How to" page [that will hopefully answer your question](https://github.com/yanickrochon/jquery.multiselect-2/wiki/Limit-the-number-of-elements-that-can-be-selected).

Please, confirm that this is what you are looking for.

**Comment by fabiocastaneda** [comment]
Hi Yanick:

Excellent!  It helped me to solve the issue.

Browser: Chrome Version 24.0.1312.57 m

Let me know if you would you like me to try with another browser? 

Thank you very much!

**Comment by yanickrochon** [comment]
Note that I'll be modifying my last example as I just realized that doing a search (filtering, then resetting the filter) will cancel the restriction. I'll think about a decent workable hack... hrm.... feature for that!

But you essentially get the idea.

**Comment by yanickrochon** [comment]
FYI : I just pushed a commit that fixes a few bugs. I also updated the wiki page and the demo to properly do what you are asking. Since I did find a few issues with the code answering this question, I thank you for your feedback and helping me make this widget even better.

**Comment by fabiocastaneda** [comment]
Hi Yanic 
,sorry to bother you.

I have tried to use groups <optgroup> with two lists but I am not able to put it to work. Could you help me out? This is what I have done so far. Thank you! 

![image](https://f.cloud.github.com/assets/3435848/154532/2ea497e8-7620-11e2-870d-8a321353d1df.png)
