### ISSUE TITLE
Ability to pass in verbiage for "selected"

### ISSUE THREAD

**Issue by bhawthorne** [yanickrochon/jquery.uix.multiselect#17]
It would be helpful it would accept overrides of "{count} select options" text.

**Comment by yanickrochon** [comment]
There is an override. Look at the [locales](https://github.com/yanickrochon/jquery.multiselect-2/tree/master/js/locales) folder. You can declare something like

```
$.extend( $.uix.multiselect.i18n[""], {
    itemsSelected: '{count} book selected',           
    itemsSelected_plural: '{count} books selected'
});
```

to replace the default strings, or declare a new "locale", for example

```
$.uix.multiselect.i18n["books"] = {
    itemsSelected: '{count} book selected',           
    itemsSelected_plural: '{count} books selected'
    //... all the other strings
};
```

and create a new multiselect using : `$(selector).multiselect({ locale: "books" });`

**Comment by yanickrochon** [comment]
No feedback, I'm closing this issue as resolved.
