### ISSUE TITLE
Add "zero" option for locales

### ISSUE THREAD

**Issue by dv-petrov** [yanickrochon/jquery.uix.multiselect#18]
Please, add locale variant to zero (selected, available, etc) options.
Two reasons for this:
1. We can write 'None available'
2. In Russian, zero rules as plural. "1 вариант, 10 вариантов, 0 вариантов" (1 option, 10 options, 0 options).

Thanks.

**Comment by yanickrochon** [comment]
Noted!

**Comment by yanickrochon** [comment]
Can you confirm that this fix the issue? Thanks!

**Comment by dv-petrov** [comment]
Yeah, thanks!

**Comment by yanickrochon** [comment]
By the way, if you can provide the russian translation, I will add it to the locales :)
