### ISSUE TITLE
When multiselect is inside a <form> all buttons cause refresh

### ISSUE THREAD

**Issue by EasyAsABC123** [yanickrochon/jquery.uix.multiselect#2]
When i have a multiselect inside a form tag the select all/deselect all/search buttons refresh the page.

**Comment by yanickrochon** [comment]
Please confirm if the last push solves this issue.

**Comment by EasyAsABC123** [comment]
not resolved for search button.

**Comment by yanickrochon** [comment]
d'oh! :)

**Comment by yanickrochon** [comment]
I also applied the fix for all buttons. It should solve it now. (I pushed in the dev branch, will merge when confirmed)

**Comment by EasyAsABC123** [comment]
resolved.
