### ISSUE TITLE
Running total of values

### ISSUE THREAD

**Issue by GeorgeC78** [yanickrochon/jquery.uix.multiselect#20]
Is there a way to put in a text box with running total of the sum of selected values on each click? I have tried to merge my existing basic multiselect add-values script and cannot get this to work. I may be missing something in API, so if so I aplologise. Great script.

**Comment by yanickrochon** [comment]
Yes, of course! This widget is merely a "skin" on top of the original SELECT option. You can get that desired sum in two ways :
1. Listen for the `multiselectChange` event and sum the options returned by `ui.optionElements`. Then add (if `ui.selected == true`) or subtract (if `ui.selected == false`) from a cached sum that you keep from previous events. For example (untested) :
   
   ```
   var cachedSum = 0;
   $(selector).bind("multiselectChange", function(evt, ui) {
       var localSum = 0;
       $.each(ui.optionElements, function(i, o) {
           localSum += parseInt( $(o).val() );
       });
       cachedSum += localSum * (ui.selected ? -1 : 1);
   
       // update whatever with cachedSum here
   });
   ```
2. Recalculate every options every time. This option requires a little more processing, but will have a better guarantee to be exact every time.
   
   ```
   var cachedSum = 0;
   $(selector).bind("multiselectChange", function(evt, ui) {
       cachedSum = 0;
       $(this).find("option:selected").each(function(i, o) {
           cachedSum += parseInt( $(o).val() );
       });
   
       // update whatever with cachedSum here
   });
   ```

Hope this helps.

**Comment by GeorgeC78** [comment]
Thank you very much, Yanick!
I had been using a change event on my original multiselect box with no success, but now I have now implemented your 2nd example and it works perfectly!
All the best. George.
