### ISSUE TITLE
[Q] Support load data by ajax?

### ISSUE THREAD

**Issue by demonslord** [yanickrochon/jquery.uix.multiselect#23]
Can't found info :(

**Comment by yanickrochon** [comment]
Is [this](https://github.com/yanickrochon/jquery.multiselect-2/wiki/Implementing-Ajax-search-filtering) a good example? If you need something more specific, I can try to add more examples.

The Ajax feature was removed from the widget core as I didn't want to make the same mistake as the previous version. Note that a plugin or extension could be written on top of the multiselect to extend it's functionality this way.

**Comment by demonslord** [comment]
yep, this is nice example ;)

Thanks.
