### ISSUE TITLE
Interpolation of options name

### ISSUE THREAD

**Issue by mauriciopasquier** [yanickrochon/jquery.uix.multiselect#34]
Would it be too much work to have an option for interpolating the name of the "options" in the locales? So instead of "selected options" you can have "selected countries".

Possible issues with pluralization and stuff :P

**Comment by yanickrochon** [comment]
See issue #17. You can simply provide a custom locale and use whatever string best fit your needs.

**Comment by mauriciopasquier** [comment]
Awesome, I hadn't thought about extend. Thanks!
