### ISSUE TITLE
ReferenceError: obj is not defined

### ISSUE THREAD

**Issue by mauriciopasquier** [yanickrochon/jquery.uix.multiselect#35]
I'm getting that error in [this line](https://github.com/yanickrochon/jquery.multiselect-2/blob/master/js/jquery-multiselect-2.0.js#L740).

It happens when I have some elements of a group selected, and try to add the remaining items from the `availables` list (with the `SelectAllGroup` button), but **only** when the group in `selected` items list is collapsed.

Both lists get empty, and doing a refresh show some incomplete state:
- The items from `available` remain there, but without a group
- The group count from `selected` includes all items

While trying to reproduce it in reverse order (from `selected` to `available`) the collapsed group in `available` is extended but nothing is added/removed.

I don't know if it's relevant, but I have repeated items in different groups (e.g. both group A and group B have an option with value 'foo' and text 'bar')

**Comment by demonslord** [comment]
Hola mauriciopasquier,
I am preparing new PR (Pull Request) for issue #32.

Best Regards.

**Comment by yanickrochon** [comment]
It shouldn't matter that you have repeating option values, each list item is bound to it's option element at create time (see the widget's [`refresh`](https://github.com/yanickrochon/jquery.multiselect-2/blob/master/js/jquery-multiselect-2.0.js#L138) method). And it should not affect that the group is collapsed. I'll take a look at it this weekend if no one found a fix for it yet.

**Comment by mauriciopasquier** [comment]
Great, thanks! I'm not very fluent in js, so..

**Comment by yanickrochon** [comment]
I _finally_ had some time this morning to take a look at it, and... I can't reproduce this problem. And since the last commit, the link ref does not point to an error prone line.

Please, validate that this issue is still confirmed.

**Comment by mauriciopasquier** [comment]
Couldn't reproduce it either :)

**Comment by yanickrochon** [comment]
Must have been fixed at some point by something else. All good then! Please, reopen if there's anything to add to this.
