### ISSUE TITLE
API : function search improvent/fix

### ISSUE THREAD

**Issue by demonslord** [yanickrochon/jquery.uix.multiselect#36]
When you use search method with some text

``` ruby
$('#multiselect').multiselect('search', { text: '2' });
```

it's work fine, but if you try searching by empty text:

``` ruby
$('#multiselect').multiselect('search', { text: '' });
```

I think it should be "reset" the filtring (show all) and empty searhField in available list.

I think I'm explicit :)

Best Regards.

**Comment by yanickrochon** [comment]
Yes, this is what it should do.

**Comment by demonslord** [comment]
Yeah, but doesn't work :(

You can see it on your demo.

**Comment by yanickrochon** [comment]
Yes, I realized that when I wrote my last comment. Will check that later on.

**Comment by demonslord** [comment]
ok, thanks ;)

**Comment by yanickrochon** [comment]
This will be part of the next relase.
