### ISSUE TITLE
Widget do not render properly

### ISSUE THREAD

**Issue by dv-petrov** [yanickrochon/jquery.uix.multiselect#39]
![snapshot1](https://f.cloud.github.com/assets/3541464/192353/6300e73c-7f60-11e2-99b3-b8af20492f3a.png)
See above image. Select element itself do not hide, and newly created divs overlaps other elements.

And you can look @ fiddle - http://jsfiddle.net/Lwznt/
What am I doing wrong?

**Comment by yanickrochon** [comment]
You have to set a `width` and `height` (with CSS) because the widget does not automatically resize itself.

See the [updated jsfiddle](http://jsfiddle.net/Lwznt/1/).

**Comment by dv-petrov** [comment]
Aah! I see! You set width and height from original select element... So I will need some magic to set right values for them.
