### ISSUE TITLE
Submit Button: Form Action not firing (Question)

### ISSUE THREAD

**Issue by GeorgeC78** [yanickrochon/jquery.uix.multiselect#42]
I have not been able to get the submit button to work. I cannot get the button to load a specified Form Action target file.

This is probably something I am doing wrong, but please confirm if this functionality is inbuilt into the script?

Many thanks!

**Comment by yanickrochon** [comment]
Please, give more info. I have no idea of what you're talking about. There is no submit button built-in the widget.

**Comment by GeorgeC78** [comment]
Thank you for the response. This was, as expected, my mistake. I have nested the widget inside an existing form, so sorry for the confusion with my question. 

For what its worth, the debug widget script as per the demo page was causing my issue, since it includes 'preventdefault' and 'return false' which was messing up my expected functionality of my form's submit button. Removing the debug widget function (or removing those lines) reenabled expected functionality. Thanks again.

**Comment by yanickrochon** [comment]
Yes, the demo page has a `onsubmit` event listener so I could display the element's submitting value. Glad you could resolve your issue :)
