### ISSUE TITLE
IE6 Graphical issues

### ISSUE THREAD

**Issue by dmill-bz** [yanickrochon/jquery.uix.multiselect#43]
Hello,

We've decided to move to this instead of the old version. We've tested the layout / Search / (de)select all functionalities (haven't tested groups) on all the following browsers:
IE6-7-8-9 FF chrome safari. 
I'm pleased to say these basic functionalities work on all browsers for us, however the layout is broken and glitchy in IE6.

I was wondering if compatibility with IE6 was something you had in mind. Or if you (and I can't blame you) were disregarding the browser.

**Comment by yanickrochon** [comment]
Not at all. IE6 is a [dying browser](http://www.ie6countdown.com/), and the world is far better off without it. jQuery has stopped support for it, and even Microsoft ask people to stop using it. My advice is that, whoever wants this compat, should be informed and convinced to let it go, for crying out load!

**Comment by dmill-bz** [comment]
That's how I feel every day, but I'm done battling it out with big company IT departments. Quick css patch it will be and I'll call it a day.
Thanks for taking the time to reply
