### ISSUE TITLE
Copy original option style 

### ISSUE THREAD

**Issue by demonslord** [yanickrochon/jquery.uix.multiselect#44]
What are think about this feature?

This gives more control over the multiselect item.

Best Regards,
Alexander Bulei

**Comment by yanickrochon** [comment]
Please, be more specific. What do you mean by "copy original option style? 

By default, OPTION elements are not rendered by the browser. They should not possess any CSS class or styles; all of that goes to the SELECT element. They may, however, possess data attributes.
