### ISSUE TITLE
How to submit the form?

### ISSUE THREAD

**Issue by howzit** [yanickrochon/jquery.uix.multiselect#46]
Not sure where the onsubmit function is? How do you make this form submit able?

**Comment by yanickrochon** [comment]
Just place create your normal form, with your select element inside, have your submit button there too. Something like

```
<form action="" method="get">
   <!--- other form elements --->
   <select id="mySelectElement" name="mySelectElement" multiple="multiple" style="width:200px">.....</select>
   <!--- yet other form elements --->
   <input type="submit" />
</form>
```

(Note that you **have** to set a specific width to the element). Then use JavaScript to style your form elements :

```
$("#mySelectElement").multiselect(options);
```

And.... just submit your form liky any other HTML form. This widget is simply a skin over the original HTML element.

**Comment by howzit** [comment]
Thanks for the reply Yanickrochon.

I had to disable these three lines to allow saving:
//                        evt.preventDefault(); evt.stopPropagation();
//
//                        $('#debug_'+k).prepend( $('<div></div>').text("Submit query = " + $(this).serialize() ) );
//
//                        return false;

I have a very long list in a number of optgroups...
How to go about to have it collapsed by default on pageload?

**Comment by yanickrochon** [comment]
You are using the demo.... that's why it wasn't working. The demo is just an example usage. You should implement your own concrete initialisation.

**Comment by howzit** [comment]
Any pointers in what & how it can be achieved?
I am a novice but very interested jquery developer.

**Comment by yanickrochon** [comment]
Sorry I got your last comment, but was caught up with other things and forgot to reply. Have you got it working?

**Comment by howzit** [comment]
Yes, thanks  yanickrochon... 
Will comment on the drop-down collapse as well...
