### ISSUE TITLE
Limit total selected options?

### ISSUE THREAD

**Issue by howzit** [yanickrochon/jquery.uix.multiselect#47]
Is there a way to limit category selections by a certain number.
Say a person wants to allow for a maximum of 5 selections at a time?

**Comment by yanickrochon** [comment]
Hi!

A similar question have been asked (see issue #13) and I've tried to come up with one example. It is certainly possible, however it is not part of the widget's core functionality. Note that, at some point, I might introduce widget extensions for such features (it will litterally add optional features without breaking any existing code, thanks to the widget factory!)

The main goal of the core functionality is to not go too far as what the original SELECT element offers. Going into a fully bloated widget is quite easy to achieve and there are still some issues to be addressed first before adding new options.

I would invest more time (I'm already late in my expected milestones) but I have projects deadlines right now that need to be looked into, first.
