### ISSUE TITLE
Search field width being set incorrectly

### ISSUE THREAD

**Issue by HackWeight** [yanickrochon/jquery.uix.multiselect#50]
When clicking the "Search" button, the search input box doesn't currently expand correctly.  I tracked it down to here:

In the `_resize` function, it is setting the search field's width to `this._headers['available'].parent().width()` but that is returning zero (minus a compsation for header button widths), so it is being set to a negative number.

I'm not sure if this is the best solution but I've changed the search field resize line to this which seems to work:
`this._searchField.width(cAv - (isToggle ? 52 : 26));`

**Comment by yanickrochon** [comment]
Will take a look at this and confirm as soon as I can!

**Comment by yanickrochon** [comment]
This will be part of the next release.
