### ISSUE TITLE
Buttons are of type submit instead of button

### ISSUE THREAD

**Issue by johnnyPescarul** [yanickrochon/jquery.uix.multiselect#51]
Yanick, I ran into the "selectAll" being trigger by "enter" key press problem similar to this closed issue: https://github.com/yanickrochon/jquery.uix.multiselect/issues/19
Having any input element of type text anywhere in the page previously to the multiselect, and pressing enter would trigger a click on any buttons associated with the multiselect control.  From my understanding (according to this: http://stackoverflow.com/questions/4763638/enter-triggers-button-click ), this is normal HTML behavior to trigger a form/button submit if the user presses the "enter" key. So the real problem is that the buttons in the multiselect control are of type submit which triggers a form submit. Apparently this is the default type of the button if you do not specify a type. So the solution would be to properly set the type of each "button" when it is created such as the selectAll button: 

.append( btnSelectAll = $('<button></button>').addClass('uix-control-right').attr('type','button')

So please go thru each button being created and add the attr('type','button'), including the search button, deselectAll, selectAll.

Thank you for this great plug-in. It works really well and saved me a lot of work.

**Comment by yanickrochon** [comment]
Thank you for the explanation of the problem and the references.
