### ISSUE TITLE
Language + Style fix

### ISSUE THREAD

**Issue by clips-ennovate** [yanickrochon/jquery.uix.multiselect#54]
I have created an dutch language file but failed to commit it.
So i'm trying it through this way.
You can download the file from this location: http://www.vitrix.nl/jquery.uix.multiselect_nl.zip

Also i needed to style individual items so i edited the _createElement function.
After " .attr("unselectable", "on")  // disable text selection on this element (IE, Opera)" i added the following code ".attr('style', optElement.attr('style'))"
This way i could add an style attribute to the option element and it would pass on to the multiselect item.

**Comment by yanickrochon** [comment]
Done! Thanks!

Concerning the `.attr("unselectable", "on")` and adding your own style, I'm afraid that this is not a good practice. `OPTION` elements have no layout, therefore you should not apply a style attribute to it. If you need to set custom styling, you may want to check out the [`optionRenderer`](https://github.com/yanickrochon/jquery.uix.multiselect/blob/master/js/jquery.uix.multiselect.js#L37) widget option (also see it's usage [here](https://github.com/yanickrochon/jquery.uix.multiselect/blob/master/js/jquery.uix.multiselect.js#L819)).
