### ISSUE TITLE
Conflict with bootstrap

### ISSUE THREAD

**Issue by brunobg** [yanickrochon/jquery.uix.multiselect#55]
This is not a bug per se, but it took me some time to track it, so perhaps it should be added to the docs.

Bootstrap conflicts with jquery UI, because both define $.fn.button(). This makes the buttons in multiselect not render correctly (no icons). 

This code reverts bootstrap's button to jquery ui's button:

``` javascript
if ($.fn.button.noConflict != undefined) {
    $.fn.button.noConflict();
}
```

**Comment by yanickrochon** [comment]
[Done](https://github.com/yanickrochon/jquery.uix.multiselect/wiki/Troubleshooting). Thankis.

**Comment by vyruz1986** [comment]
Sorry for asking, but where do I put this code?
I'm having this issue on my site (blank icon buttons) and I'm using Bootstrap v3.

Thanks in advance!

**Comment by yanickrochon** [comment]
Theoretically anywhere before you instantiate the `multiselect` widget. But I haven't tried any of this as I never mixed jQuery UI with Bootstrap.

**Comment by vyruz1986** [comment]
That did the trick, thanks!
