### ISSUE TITLE
Search within group names

### ISSUE THREAD

**Issue by lwoodring** [yanickrochon/jquery.uix.multiselect#56]
Would like an option for the 'Search' field to also search within the <optgroup> names.  For example, in your demo, if you enter "United" in the search field, it would include all of the items in the "United Kingdom" and "United States" groups.

**Comment by yanickrochon** [comment]
This will get resolved with issue #15. Using a custom search callback, the implementation will be able to return true or false if an option element satisfies or not the search term.
