### ISSUE TITLE
can we use a jquery-ui custom build?

### ISSUE THREAD

**Issue by lionkeng** [yanickrochon/jquery.uix.multiselect#59]
Do you know which modules in jquery-ui that jquery.uix.multiselect depends on? I was wondering if I can can include a smaller custom built jquery-ui.

thanks!
Keng

**Comment by yanickrochon** [comment]
On the top of my head, `draggable`, `droppable`, `sortable` and `effects` are all optional if you disable the options, `button` is mandatory. I've never tested it with a custom build, to know exactly what is actually needed. I've never had to down size the library ever.

Note that if you can use a CDN source, it not only reduce your hosting bandwidth, but also speed up the client's page at load time as the file is most likely in the browser cache already.

**Comment by yanickrochon** [comment]
Could you confirm that this question was answered? Or if you have other concern about this issue?

Thanks.

**Comment by lionkeng** [comment]
Yes. Thank you for you prompt response.
 Excellent tool.
Thx!
-KL
