### ISSUE TITLE
search?

### ISSUE THREAD

**Issue by jmelnik** [yanickrochon/jquery.uix.multiselect#6]
I'm sure I'm missing something somewhere, but the search feature doesn't appear to do anything-- in the previous version it filtered the available items list.

And it's not my implementation because it doesn't seem to work at http://mind2soft.com/labs/jquery/multiselect/ either (unless it's a bug in all the browsers I tested in).

In the demo I see that the multiselect search event is being triggered-- so I'm guessing I need to trigger or do the filtering myself based on the event provided, but it wasn't clear from the docs.

Any info/suggestions would be greatly appreciated!

**Comment by yanickrochon** [comment]
Interesting! I have spent a lot of time on the sortable / droppable feature that I have forgot to test the feature that has been there since the very beginning! In any case, it was a simple boolean check mistake. All supposed to work now! Thank you for spotting this!

**Comment by jmelnik** [comment]
Holy Smokes that was Fast!!!!!

Thanks for taking care of it already.

**Comment by yanickrochon** [comment]
BTW : the `multiselectSearch` event is fired for you to modify the search value (modify `ui.text`) or use the event object's `preventDefault()` function to cancel the search, if you want to perform some Ajax search (like in the first version), update the original `SELECT` element, then call `refresh` and `search` back again (calling the `search` method directly will **not** trigger an event by default!)

I shall have to write some "How to" now :)
