### ISSUE TITLE
How to deselect selected options through code

### ISSUE THREAD

**Issue by ahmed-jawad** [yanickrochon/jquery.uix.multiselect#60]
How can I reset the selected options via code for multiple multiselect list on the same page? I want to move all the selected options back to available options list for every multiselect list on the page at once?

**Comment by yanickrochon** [comment]
Use this :

```
$("select.uix-multiselect-original")
     .find("option[selected]").prop("selected", false).end()
     .multiselect("refresh");
```

And it should reset all options for all multiselect instances and refresh everything.
