### ISSUE TITLE
How to hide the parent OPTGROUP when the child data is zero after searching

### ISSUE THREAD

**Issue by ramchand87** [yanickrochon/jquery.uix.multiselect#61]
Hi,
 I am using the mutli-select in my application. By default I will be getting parent and child OPT Groups with data.If suppose user searches using search text box and matching child group records are not found It currently shows empty Parents groups. My requirement is that in this case is that parent OPTGROUP should be hidden. Can you please tell me how this can be done ?

**Comment by yanickrochon** [comment]
Sorry for the late response. Right now, and by default, there is no option to do this. But this feature is basically the same as issue #28. It'll get implemented at some point in this milestone (2.1).
