### ISSUE TITLE
Event fired after multiselect is done?

### ISSUE THREAD

**Issue by lebolo** [yanickrochon/jquery.uix.multiselect#62]
Is there an event fired _after_ the multiselect is done (i.e. after all the option elements have been created).

Specifically, I'd like to add a tooltip to each element right after it's created, but the jQuery UI Widget create event is triggered before the elements are displayed (my jQuery selection fails since the option elements don't exist yet).

Hope this is the right 'forum' for this question.

**Comment by yanickrochon** [comment]
Yes, this is the right question for this. I think I know how to reolve this in a very easy way (and would also give a slightly better solution to issue #48) I'll update the code in a few minutes.

Basically, just pass an option `created` at widget creation; a function that will be called once everything is loaded and ready.

**Comment by lebolo** [comment]
Worked perfectly for my situation. Great tool, thanks for everything!
