### ISSUE TITLE
Left > Right flow

### ISSUE THREAD

**Issue by Unibozu** [yanickrochon/jquery.uix.multiselect#65]
Hi Yanick,

It would be great to be able to switch the two panels place. Most of Multiselect are usually  from left (available elements) to right (selected choices). 

Most of users get use to particular flow with widgets, and thus one of my colleagues told me he had some issues on a project using your widget (some complains of end users who didn't understand why it was inverted).

Do you think, it would be a big work to change it ? I'm thinking of doing it for my project, and of course, I'd consider pushing it after if it is done.

Thank you

**Comment by Unibozu** [comment]
note for myself : spend more time to check the doc/api :)
sorry for the issue

**Comment by yanickrochon** [comment]
Glad you found that out so quickly ;)
