### ISSUE TITLE
helps me a lot

### ISSUE THREAD

**Issue by ghost** [yanickrochon/jquery.uix.multiselect#68]
Thanks for sharing your code and ideas as it is best multi selection on an iPad I have seen so far and I will try to make it run on my site. My only issue is when I look at it from an iPhone there really isn't enough space to have 2 columns. Is there an option or something that will allow me to collapse into one column with both selected an non-selected values?

**Comment by yanickrochon** [comment]
Hi, I do not own an iPad and I'm glad to hear that you're testing the widget on it (and it works). I actually haven't got to the mobile testing yet, and it is in planning for this current milestone... along with ARIA attributes (HTML5), etc.

What do you mean by "collapse into one column with both selected and non-selected values"? Would you have some mock up interface to demo your idea? Or do you means having one column and a simple "click-to-select" list interface?

Also, as a temporary (or permanent) solution, there is an option to set the layout of the lists into a vertical position. For example, a landscape layout

```
$(selector).multiselect('option', 'availableListPosition', 'right').multiselect('refresh');  // default
```

and a portrait layout

```
$(selector).multiselect('option', 'availableListPosition', 'top').multiselect('refresh');
```

**Comment by ghost** [comment]
Hi Yanick,

Thank you very much for your answer. I am sure your portrait option will work perfect. Looks great. In fact I was looking for a simple click-to-select list interface as the problem on an iPad is that it does not render the size option the same way as does IE, firefox ...

But your portrait option will do perfect. I'll play around with it and report back.  

:-) LarsP

**Comment by ghost** [comment]
Hi Yanick,

Your suggestion with the portrait layout was very helpful and I hope you can help me with one more question.

When I pass on selected values in <form method=”post”> a commaseparated value-list I passed on, but my option list has values that contains commas. Is it possible pass on a semicolon separated list instead?

Best regards

**Comment by yanickrochon** [comment]
Wow! This reply is very late :( 

This widget does not modify the form element's submission, it's merely a skin and sugar on top of the original element. I am closing this. But if you still have the issue, or anything to comment on it, please do so, and I'll take a look at it.
