### ISSUE TITLE
Ability to add hover over text to selected & available items [ENHANCEMENT]

### ISSUE THREAD

**Issue by zoltan-fedor** [yanickrochon/jquery.uix.multiselect#74]
Hi,
It would be nice to have the ability to add hover over text to the selected and available items in the list. In case if long text would make it too heavy, then the ability to load the hover over text via ajax might be desired.
Thanks

**Comment by yanickrochon** [comment]
You can get around this by doing :

```
// remplace '#multiselect' with your actual multiselect element selector
$("#multiselect").next().on("mouseover", ".option-element", function(evt) {  
    /* evt.currentTarget is the DIV element for the list option */
});
```

If you want more control over the rendering of each element, take a look at `optionRenderer` (See the [wiki](https://github.com/yanickrochon/jquery.uix.multiselect/wiki/API-Documentation)).

**Comment by zoltan-fedor** [comment]
Thanks, that has worked!
(actually used mouseenter and not mouseover, but otherwise about the same)
