### ISSUE TITLE
Ability to add items to selected options through programming?

### ISSUE THREAD

**Issue by sairangam** [yanickrochon/jquery.uix.multiselect#87]
Hello Everyone,

Please let me know if we have ability to add the items to selected options dynamically through programming ,if yes please send me the code how to add.
## Cheers,

Ranga M

**Comment by yanickrochon** [comment]
Hi, if you had skimmed through the Wiki, you'd have stumbled across [your answer](https://github.com/yanickrochon/jquery.uix.multiselect/wiki/Programmatically-de-select-option-values). :)
