### ISSUE TITLE
Bootstrap compatibility

### ISSUE THREAD

**Issue by Poil** [yanickrochon/jquery.uix.multiselect#91]
Hi,

It will be cool to have this widget compatible with bootstrap (today the elements sizes are bad)
Perhaps adding a size in percent can be a solution;

Best regards

**Comment by yanickrochon** [comment]
Unfortunately, jQuery UI and Bootstrap don't mix well together. In fact, they shouldn't be used together!

A new version of the widget should be rolled, for Bootstrap. While I _am_ actually working more and more with that framework, and less with jQuery UI... I have no time to maintain such projects. I still have to maintain the current implementation (i.e. finish it!).

**Comment by Poil** [comment]
It's not easy to have both, some ppl start some work. DataTables have js+css wrapper, we can also find a jquery ui bootstrap theme (https://github.com/jquery-ui-bootstrap/jquery-ui-bootstrap/).

**Comment by Poil** [comment]
Just an update ... with jquery-ui-bootstrap and forcing cSl/cAv to 45%/55% your plugin is usable, I now need to understand how the height is calculated ... but all elements are rightly aligned/sized :)

**Comment by yanickrochon** [comment]
Good to hear that! Just create a branch (i.e. `bootstrap-integration`) and I'll add it to the repository.

**Comment by yanickrochon** [comment]
I will close this as a Bootstrap solution is not viable. This plugin was made for jQuery UI and Bootstrap has it's own set of UI classes, etc.

BTW: for a Bootstrap equivalent, I strongly suggest [select2](https://ivaynberg.github.io/select2/).

**Comment by Poil** [comment]
Fyi, 

I've removed all your width in px code to replace with % and some other little tweak, I've got this http://web.quakelive.fr/CGraphz/index.php?module=config&component=project&f_id_config_project=2#project_server
(admin/pass)

Like that I only need a parent element that fix the width. I only have some problem to have dynamic height so I've fixed it to 200px.
